-- À exécuter une fois par l'administrateur après le setup RAW/Azure du README.
-- Remplacer <VOTRE_UTILISATEUR_DBT> et <VOTRE_UTILISATEUR_AIRFLOW>.
USE ROLE SECURITYADMIN;
CREATE ROLE IF NOT EXISTS DBT_TRANSFORMER;
CREATE ROLE IF NOT EXISTS AIRFLOW_INGESTOR;
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE DBT_TRANSFORMER;
GRANT USAGE ON DATABASE RAW TO ROLE DBT_TRANSFORMER;
GRANT USAGE ON SCHEMA RAW.SOURCES TO ROLE DBT_TRANSFORMER;
GRANT SELECT ON TABLE RAW.SOURCES.COMPANY_RAW TO ROLE DBT_TRANSFORMER;
GRANT SELECT ON TABLE RAW.SOURCES.JOB_POSTINGS_RAW TO ROLE DBT_TRANSFORMER;
GRANT SELECT ON TABLE RAW.SOURCES.SKILLS_RAW TO ROLE DBT_TRANSFORMER;
GRANT SELECT ON TABLE RAW.SOURCES.SKILLS_JOBS_RAW TO ROLE DBT_TRANSFORMER;
GRANT USAGE, CREATE SCHEMA ON DATABASE ANALYTICS TO ROLE DBT_TRANSFORMER;
GRANT ROLE DBT_TRANSFORMER TO USER <VOTRE_UTILISATEUR_DBT>;

GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE AIRFLOW_INGESTOR;
GRANT USAGE ON DATABASE RAW TO ROLE AIRFLOW_INGESTOR;
GRANT USAGE ON SCHEMA RAW.SOURCES TO ROLE AIRFLOW_INGESTOR;
GRANT USAGE ON STAGE RAW.SOURCES.AZURE_JOBS_STAGE TO ROLE AIRFLOW_INGESTOR;
GRANT USAGE ON FILE FORMAT RAW.SOURCES.CSV_FORMAT TO ROLE AIRFLOW_INGESTOR;
GRANT INSERT, SELECT ON TABLE RAW.SOURCES.COMPANY_RAW TO ROLE AIRFLOW_INGESTOR;
GRANT INSERT, SELECT ON TABLE RAW.SOURCES.JOB_POSTINGS_RAW TO ROLE AIRFLOW_INGESTOR;
GRANT INSERT, SELECT ON TABLE RAW.SOURCES.SKILLS_RAW TO ROLE AIRFLOW_INGESTOR;
GRANT INSERT, SELECT ON TABLE RAW.SOURCES.SKILLS_JOBS_RAW TO ROLE AIRFLOW_INGESTOR;
GRANT ROLE AIRFLOW_INGESTOR TO USER <VOTRE_UTILISATEUR_AIRFLOW>;

-- Ces utilisateurs dédiés ne doivent pas avoir ACCOUNTADMIN/COMPUTE_ROLE.
-- dbt crée et possède ses schémas DBT_DEV, DBT_DEV_STAGING, DBT_DEV_MARTS,
-- DBT_DEV_SNAPSHOTS dans ANALYTICS. Aucun droit d'écriture sur RAW.
